name: IMO / Agent Intake
description: Any
labels: ["IMO"]
projects: ["ZacheryFaria/2"]
assignees:
  - ZacheryFaria
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What piece of software does this concern?
      options:
        - Agent Dashboard + AAA
        - Aardvark + Benchmark
        - Aardvark (Non-IMO Agents)
      default: 0
    validations:
      required: true
  - type: textarea
    id: the-request
    attributes:
      label: 'What is the request?'
      description: 'Please share any expected timelines, deadlines, expected impact, etc.'
      placeholder: 'Please share any expected timelines, deadlines, expected impact, etc.'
    validations:
      required: true
